spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/coroutine
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update # 没有表新建，有表更新操作
    show-sql: true # 控制台显示建表语句
  r2dbc:
    url: r2dbc:mysql://192.168.1.102:3306/coroutine
    username: root
    password: 123456
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
#  data:
#    mongodb:
#      uri: mongodb://192.168.2.53:27017/reactive




logging:
  level:
    org.springframework.data.r2dbc: DEBUG